$('.owl-carousel').owlCarousel({
    loop:true,
    margin:100,
    dots:false,
    nav:false,
    mouseDrag:false,
    autoplay:false,
    animateOut: 'slideOutUp',
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
});